name: Deploy Azure Storage Account

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (dev, staging, prod)"
        required: true
        default: "dev"
      storage_account_name:
        description: "Storage Account Name"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Setup Azure CLI
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Select the correct tfvars file
    - name: Set Environment Variables
      run: |
        echo "ENV_TFVARS=${{ github.event.inputs.environment }}.tfvars" >> $GITHUB_ENV

    # Plan the Terraform deployment
    - name: Terraform Plan
      run: terraform plan -var-file=${{ env.ENV_TFVARS }}

    # Apply the Terraform deployment
    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file=${{ env.ENV_TFVARS }} -var="storage_account_name=${{ github.event.inputs.storage_account_name }}"
